version: '3'
services:
  bundle:
    image: jekyll/jekyll
    command: bundle update
    volumes:
      - $PWD:/srv/jekyll

  build:
    image: jekyll/jekyll
    command: jekyll build -d /tmp/jekyll-output
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/public:/tmp/jekyll-output

  serve:
    image: jekyll/jekyll
    command: jekyll serve --draft -d /tmp/jekyll-output
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/public:/tmp/jekyll-output
    ports:
      - 4000:4000
