version: '3'
services:
  bundle:
    build: .
    command: bundle update
    volumes:
      - $PWD/vendor/bundle:/usr/local/bundle
      - $PWD:/srv/jekyll

  build:
    build: .
    command: jekyll build -d /tmp/jekyll-output
    volumes:
      - $PWD/vendor/bundle:/usr/local/bundle
      - $PWD:/srv/jekyll
      - $PWD/public:/tmp/jekyll-output

  serve:
    build: .
    command: jekyll serve --host 0.0.0.0 --draft -d /tmp/jekyll-output
    volumes:
      - $PWD/vendor/bundle:/usr/local/bundle
      - $PWD:/srv/jekyll
      - $PWD/public:/tmp/jekyll-output
    ports:
      - 4000:4000
