version: '3'
services:
  site:
    image: nginx:alpine
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/site-output:/var/www/jekyll:ro
      - $PWD/logs:/var/log/nginx
    ports:
      - 8088:80

  build:
    image: jekyll/jekyll
    command: jekyll build -w -d /tmp/jekyll-output
    volumes:
      - $PWD/site:/srv/jekyll
      - $PWD/site-output:/tmp/jekyll-output
