source "https://rubygems.org"

gem "jekyll", "~> 3.8"

# Theme
gem "jekyll-theme-hydeout", "~> 3.7"

# Plugins
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.10"
   gem "jekyll-gist", "~> 1.5"
   gem "jekyll-paginate", "~> 1.1"
   gem "jekyll-sitemap", "~> 1.2"
   gem "public_suffix", "3.0.2"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
